name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a0e7f47cb181111b91583c57e50cb88b2b503b15667742e771ae8c70b6b81d"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
