name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b9c62111056764534b60e19c2741d5b33ff1d2c10dcc1594b5d9dec68651a5"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
