name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12a3ce4c26c7394c9743b5984c00d403f462ff5ee6df1161b623a9534f52d177"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
