name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f657c21d483b600ea9ebb0be4a3a6d00e3e8bcc1e17630cb5f2b1bf7d5d42a9"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
