name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c18baadb90189e38268715defbff39679453eb1917da0f44dc3f3635cdc241d"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
