name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56cba14cbe5d783846e3cded331947fc846dca33e4f9cc57f2cdd25a512e40f4"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
