name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b1fb1e881bded3f6619596eb599eaa628c6e0322a18f81f4f6f1af14e0eeaf2"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
