name = "Farming"
author = "Jonatan Steuernagel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d31343a7f0027161f2ccb83995e85a6775202fd8722bcbaa704a9c75c996bcc"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
